export enum assetSymbols {
  USDC = "USDC",
  USDT = "USDT",
  WBTC = "WBTC",
  mBTC = "mBTC",
  ezETH = "ezETH",
  weETH = "weETH",
  wrsETH = "wrsETH",
  WETH = "WETH",
  wstETH = "wstETH",
  cbETH = "cbETH",
  AERO = "AERO",
  eUSD = "eUSD",
  bsdETH = "bsdETH",
  SNX = "SNX",
  OP = "OP",
  LUSD = "LUSD",
  SOV = "SOV",
  tBTC = "tBTC",
  RSR = "RSR"
}
